/*
 * This source file was generated by the Gradle 'init' task
 */
package org.zane.newpipe;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.imageio.ImageIO;
import javax.swing.*;
import org.zane.newpipe.page.ChannelPage;
import org.zane.newpipe.page.MainViewPort;
import org.zane.newpipe.page.MainViewPort.NevigateOpation;
import org.zane.newpipe.page.SearchResultPage;
import org.zane.newpipe.page.VideoPage;
import org.zane.newpipe.ui.IconRes;
import org.zane.newpipe.util.VideoUtil;
import uk.co.caprica.vlcj.factory.discovery.NativeDiscovery;

public class App extends JFrame {

    private JButton searchButton;
    private SearchResultPage searchResultPage;
    private VideoPage videoPage;
    private JTextField searchField;
    private MainViewPort mainViewPort;
    private ChannelPage channelPage;

    public App(String searchQuery) {
        this(false);
        searchField.setText(searchQuery);
        searchButton.doClick();
    }

    public App() {
        this(true);
    }

    private App(boolean showDefault) {
        NativeDiscovery nd = new NativeDiscovery();
        if (nd.discover()) {
            VideoUtil.setVlcPath(nd.discoveredPath());
        }
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setTitle("NewPipe");
        try {
            this.setIconImage(
                ImageIO.read(
                    this.getClass().getResourceAsStream("/ic_launcher.png")
                )
            );
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.setMinimumSize(new Dimension(750, 500));
        this.addWindowListener(
            new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(
                    java.awt.event.WindowEvent windowEvent
                ) {
                    if (
                        JOptionPane.showConfirmDialog(
                            App.this,
                            "Are you sure you want to close this window?",
                            "Close NewPipe?",
                            0,
                            3
                        ) ==
                        0
                    ) {
                        App.this.setVisible(false);
                        System.exit(0);
                    }
                }
            }
        );
        this.setLayout(new BorderLayout());

        JPanel searchbar = new JPanel(new BorderLayout());

        searchbar.setBackground(new Color(255, 0, 0));
        this.add(searchbar, BorderLayout.NORTH);
        JButton backBtn = new JButton(IconRes.ARROW_BACK_ICOM);
        backBtn.setEnabled(false);
        backBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        backBtn.setBackground(new Color(255, 0, 0));
        backBtn.setOpaque(false);
        backBtn.addActionListener(e -> mainViewPort.back());
        searchbar.add(backBtn, BorderLayout.LINE_START);
        searchField = new JTextField(10);

        searchbar.add(searchField, BorderLayout.CENTER);
        searchButton = new JButton();
        searchButton.setOpaque(false);
        searchButton.setBackground(new Color(255, 0, 0));
        searchButton.setIcon(IconRes.SEARCH_ICOM);
        searchButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        searchbar.add(searchButton, BorderLayout.LINE_END);

        mainViewPort = new MainViewPort(
            backBtn::setEnabled,
            searchButton::setEnabled,
            searchField::setText,
            showDefault
        );
        JScrollPane mainContent = new JScrollPane(
            JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER
        );
        mainContent.setViewport(mainViewPort);
        //mainContent.setMinimumSize(new Dimension(1000, 500));
        this.add(mainContent, BorderLayout.CENTER);

        searchButton.addActionListener(this::onSearchAction);
        searchField.addActionListener(this::onSearchAction);
    }

    public void onSearchAction(ActionEvent e) {
        MainViewPort.Page newPage;
        String qurey = searchField.getText().trim();
        try {
            URI uri = new URI(qurey);
            String host = uri.getHost();
            String path = uri.getPath();
            if (host == null) {
                throw new URISyntaxException(qurey, "no Host");
            }
            if (path == null) {
                throw new URISyntaxException(qurey, "no Path");
            }
            switch (host.toLowerCase()) {
                case "youtube.com":
                case "www.youtube.com":
                case "m.youtube.com":
                    String[] paths = path.split("/", 3);
                    if (paths.length > 1) {
                        switch (paths[1].toLowerCase()) {
                            case "watch":
                                newPage = MainViewPort.Page.VIDEO;
                                break;
                            case "hashtag":
                                newPage = MainViewPort.Page.SEARCH;
                                qurey = "#" + qurey;
                                break;
                            default:
                                if (paths[1].charAt(0) == '@') {
                                    newPage = MainViewPort.Page.CHANNEL;
                                } else {
                                    newPage = MainViewPort.Page.SEARCH;
                                }
                        }
                    } else {
                        {
                            newPage = MainViewPort.Page.SEARCH;
                        }
                    }
                    break;
                case "youtu.be":
                    newPage = MainViewPort.Page.VIDEO;
                    break;
                default:
                    newPage = MainViewPort.Page.SEARCH;
            }
        } catch (URISyntaxException err) {
            newPage = MainViewPort.Page.SEARCH;
        }
        mainViewPort.nevigate(new NevigateOpation(newPage, qurey));
    }
}
