/*
 * This source file was generated by the Gradle 'init' task
 */
package org.zane.newpipe;

import java.awt.*;
import java.awt.event.ActionEvent;
import javax.swing.*;
import org.schabi.newpipe.extractor.NewPipe;

public class App extends JFrame {

    public enum Page {
        SEARCH,
        VIDEO,
        CHANNEL,
    }

    private JButton searchButton;
    private SearchResultPage searchResultPage;
    private VideoPage videoPage;
    private JTextField searchField;
    private JScrollPane mainContent;
    private Page currentPage;
    private ChannelPage channelPage;

    public App() {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setTitle("NewPipe");
        this.setMinimumSize(new Dimension(750, 500));

        this.addWindowListener(
            new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(
                    java.awt.event.WindowEvent windowEvent
                ) {
                    if (
                        javax.swing.JOptionPane.showConfirmDialog(
                            App.this,
                            "Are you sure you want to close this window?",
                            "Close NewPipe?",
                            0,
                            3
                        ) ==
                        0
                    ) {
                        App.this.setVisible(false);
                        System.exit(0);
                    }
                }
            }
        );
        this.setLayout(new BorderLayout());
        JPanel searchbar = new JPanel();
        searchbar.setBackground(new Color(255, 0, 0));
        this.add(searchbar, BorderLayout.NORTH);
        searchField = new JTextField(10);

        searchbar.add(searchField);
        searchButton = new JButton();
        searchButton.setText("search");
        searchbar.add(searchButton);
        JPanel defultPage = new JPanel(new BorderLayout());
        defultPage.add(
            new JLabel("Try searching to get started", SwingConstants.CENTER),
            BorderLayout.CENTER
        );
        mainContent = new JScrollPane(
            defultPage,
            JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER
        );

        //mainContent.setMinimumSize(new Dimension(1000, 500));
        this.add(mainContent, BorderLayout.CENTER);

        searchResultPage = new SearchResultPage(this);
        videoPage = new VideoPage(this);
        channelPage = new ChannelPage(this);
        this.setVisible(true);
        searchButton.addActionListener(e ->
            nevigate(Page.SEARCH, searchField.getText())
        );
    }

    public void nevigate(Page page, String query) {
        if (currentPage != null) {
            switch (currentPage) {
                case VIDEO:
                    videoPage.stop();
                    break;
                case SEARCH:
                    break;
            }
        }

        switch (page) {
            case SEARCH:
                searchButton.setEnabled(false);
                searchResultPage.search(query, () -> {
                    searchButton.setEnabled(true);
                });
                mainContent.setViewportView(searchResultPage);
                break;
            case VIDEO:
                mainContent.setViewportView(videoPage);
                videoPage.showVideo(query);
                //this.pack();
                break;
            case CHANNEL:
                mainContent.setViewportView(channelPage);
                channelPage.ShowChannel(query);
        }
        mainContent.doLayout();
        currentPage = page;
    }

    public static void main(String[] args) {
        NewPipe.init(new Downloader());
        String[][] styleKey = {
            {
                "OptionPane.background",
                "InternalFrame.background",
                "Panel.background",
                "Frame.background",
            },
            {
                "TextField.background",
                "Label.background",
                "PasswordField.background",
            },
        };
        String[] whiteStyle = {
            "RadioButton.foreground",
            "TextArea.foreground",
            "OptionPane.messageForeground",
            "Label.foreground",
            "TextField.foreground",
            "Button.foreground",
            "TextField.caretForeground",
            "PasswordField.foreground",
            "PasswordField.caretForeground",
        };
        for (int i = 0; i < 3; i++) {
            UIManager.put(styleKey[0][i], new Color(10, 10, 10));
            UIManager.put(styleKey[1][i], new Color(50, 50, 50));
        }
        for (String i : whiteStyle) {
            UIManager.put(i, new Color(255, 255, 255));
        }
        UIManager.put("OptionPane.cancelButtonText", "Back");
        UIManager.put("Button.background", new Color(60, 60, 60));
        UIManager.put("RadioButton.background", new Color(10, 10, 10));
        UIManager.put("Button.select", new Color(100, 100, 100));
        UIManager.put(
            "TextField.border",
            BorderFactory.createLineBorder(new Color(50, 50, 50))
        );
        UIManager.put(
            "Button.border",
            BorderFactory.createLineBorder(new Color(10, 10, 10))
        );
        UIManager.put(
            "PasswordField.border",
            BorderFactory.createLineBorder(new Color(50, 50, 50))
        );
        SwingUtilities.invokeLater(() -> {
            App main = new App();
        });

        /* */
    }
}
