/*
 * This source file was generated by the Gradle 'init' task
 */
package org.zane.newpipe;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import javax.swing.*;
import org.schabi.newpipe.extractor.ServiceList;
import org.schabi.newpipe.extractor.exceptions.ExtractionException;
import org.schabi.newpipe.extractor.suggestion.SuggestionExtractor;
import org.zane.newpipe.page.MainViewPort;
import org.zane.newpipe.page.MainViewPort.NavigateOption;
import org.zane.newpipe.ui.IconRes;

public class App extends JFrame {

    private JButton searchButton;
    private JTextField searchField;
    private MainViewPort mainViewPort;
    private JPanel searchbar;
    private static App app;
    private boolean isSuggestionMenuFocus = false;
    private JPopupMenu suggestionMenu;

    public static App getInstance() {
        return App.app;
    }

    public App(String searchQuery) {
        this(false);
        searchField.setText(searchQuery);
        searchButton.doClick();
    }

    public App() {
        this(true);
    }

    private App(boolean showDefault) {
        App.app = this;

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setTitle("NewPipe");

        this.setIconImage(IconRes.LAUNCHER_ICON);
        this.setMinimumSize(new Dimension(750, 500));
        this.addWindowListener(
            new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(
                    java.awt.event.WindowEvent windowEvent
                ) {
                    if (
                        JOptionPane.showConfirmDialog(
                            App.this,
                            "Are you sure you want to close this window?",
                            "Close NewPipe?",
                            0,
                            3
                        ) ==
                        0
                    ) {
                        App.this.setVisible(false);
                        App.this.dispose();
                        System.exit(0);
                    }
                }
            }
        );
        this.setLayout(new BorderLayout());

        searchbar = new JPanel(new BorderLayout());

        searchbar.setBackground(IconRes.YOUTUBE_COLOUR);
        this.add(searchbar, BorderLayout.NORTH);
        JButton backBtn = new JButton(IconRes.ARROW_BACK_ICON);
        backBtn.setEnabled(false);
        backBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        backBtn.setBackground(IconRes.YOUTUBE_COLOUR);
        backBtn.setOpaque(false);
        backBtn.addActionListener(e -> mainViewPort.back());
        searchbar.add(backBtn, BorderLayout.LINE_START);
        searchField = new JTextField(10);
        suggestionMenu = new JPopupMenu();

        searchbar.add(searchField, BorderLayout.CENTER);
        SuggestionExtractor suggestionExtractor =
            ServiceList.YouTube.getSuggestionExtractor();
        searchField.add(suggestionMenu);
        searchField.setComponentPopupMenu(suggestionMenu);

        searchField.addFocusListener(
            new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent fe) {
                    if (
                        !suggestionMenu.isVisible() &&
                        suggestionMenu.getComponentCount() > 0
                    ) {
                        Rectangle bounds = searchField.getBounds();
                        // Show the popup at (x, y + height) relative to the text field
                        suggestionMenu.setFocusable(false);
                        suggestionMenu.show(searchField, 0, bounds.height);
                        suggestionMenu.setFocusable(true);
                        //searchField.requestFocusInWindow();
                    }
                }

                @Override
                public void focusLost(FocusEvent fe) {
                    if (fe.isTemporary()) return;
                    suggestionMenu.setVisible(false);
                }
            }
        );
        searchField.addKeyListener(
            new KeyAdapter() {
                private boolean isSetText = false;

                @Override
                public void keyPressed(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                        Component[] c = suggestionMenu.getComponents();
                        if (c.length > 0) {
                            c[0].requestFocus();
                        }
                    }
                }

                @Override
                public void keyTyped(KeyEvent e) {
                    if (
                        isSetText && e.getKeyCode() == KeyEvent.VK_ENTER
                    ) return;
                    new Thread(() -> {
                        try {
                            List<String> suggestionList =
                                suggestionExtractor.suggestionList(
                                    searchField.getText()
                                );
                            SwingUtilities.invokeLater(() -> {
                                suggestionMenu.removeAll();
                                for (String suggestion : suggestionList) {
                                    JMenuItem suggestionMenuItem =
                                        new JMenuItem(suggestion);
                                    suggestionMenuItem.addActionListener(ee -> {
                                        suggestionMenu.setVisible(false);
                                        isSetText = true;
                                        searchField.setText(suggestion);
                                        isSetText = false;
                                    });
                                    suggestionMenu.add(suggestionMenuItem);
                                }
                                suggestionMenu.revalidate();
                                if (!suggestionMenu.isVisible()) {
                                    Rectangle bounds = searchField.getBounds();
                                    // Show the popup at (x, y + height) relative to the text field
                                    suggestionMenu.setFocusable(false);
                                    suggestionMenu.show(
                                        searchField,
                                        0,
                                        bounds.height
                                    );
                                    suggestionMenu.setFocusable(true);
                                }
                            });
                        } catch (ExtractionException | IOException ee) {
                            ee.printStackTrace();
                        }
                    })
                        .start();
                }
            }
        );
        searchButton = new JButton();
        searchbar.setFocusable(true);
        searchButton.setOpaque(false);
        searchButton.setBackground(IconRes.YOUTUBE_COLOUR);
        searchButton.setIcon(IconRes.SEARCH_ICON);
        searchButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        searchbar.add(searchButton, BorderLayout.LINE_END);

        mainViewPort = new MainViewPort(
            backBtn::setEnabled,
            searchButton::setEnabled,
            searchField::setText,
            showDefault
        );
        JScrollPane mainContent = new JScrollPane(
            JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER
        );
        mainContent.setViewport(mainViewPort);
        //mainContent.setMinimumSize(new Dimension(1000, 500));
        this.add(mainContent, BorderLayout.CENTER);

        searchButton.addActionListener(this::onSearchAction);
        searchField.addActionListener(this::onSearchAction);
    }

    public void setSearchbarVisible(boolean visible) {
        searchbar.setVisible(visible);
    }

    public void onSearchAction(ActionEvent e) {
        MainViewPort.Page newPage;

        mainViewPort.requestFocus();
        String qurey = searchField.getText().trim();
        try {
            URI uri = new URI(qurey);
            String host = uri.getHost();
            String path = uri.getPath();
            if (host == null) {
                throw new URISyntaxException(qurey, "no Host");
            }
            if (path == null) {
                throw new URISyntaxException(qurey, "no Path");
            }
            switch (host.toLowerCase()) {
                case "youtube.com":
                case "www.youtube.com":
                case "m.youtube.com":
                    String[] paths = path.split("/", 3);
                    if (paths.length > 1) {
                        switch (paths[1].toLowerCase()) {
                            case "watch":
                                newPage = MainViewPort.Page.VIDEO;
                                break;
                            case "hashtag":
                                newPage = MainViewPort.Page.SEARCH;
                                qurey = "#" + qurey;
                                break;
                            default:
                                if (paths[1].charAt(0) == '@') {
                                    newPage = MainViewPort.Page.CHANNEL;
                                } else {
                                    newPage = MainViewPort.Page.SEARCH;
                                }
                        }
                    } else {
                        {
                            newPage = MainViewPort.Page.SEARCH;
                        }
                    }
                    break;
                case "youtu.be":
                    newPage = MainViewPort.Page.VIDEO;
                    break;
                default:
                    newPage = MainViewPort.Page.SEARCH;
            }
        } catch (URISyntaxException err) {
            newPage = MainViewPort.Page.SEARCH;
        }
        mainViewPort.navigate(new NavigateOption(newPage, qurey));
    }
}
