/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

        // This dependency is used by the application.
    implementation(libs.guava)
    implementation("com.github.teamnewpipe:NewPipeExtractor:v0.26.0")
    implementation("uk.co.caprica:vlcj:4.12.1")
    val flatlafVersion = "3.7.1"
    implementation( "com.formdev:flatlaf:${flatlafVersion}" )
    implementation( "com.formdev:flatlaf:${flatlafVersion}:linux-x86_64@so" )
    implementation( "com.formdev:flatlaf:${flatlafVersion}:macos-arm64@dylib" )
    implementation( "com.formdev:flatlaf:${flatlafVersion}:macos-x86_64@dylib" )
    implementation( "com.formdev:flatlaf:${flatlafVersion}:windows-x86_64@dll" )

        // 32-bit (not needed if you bundle a 64-bit JRE with your application)
    implementation( "com.formdev:flatlaf:${flatlafVersion}:windows-x86@dll" )

        // ARM 64-bit (not needed if your application does not support Windows on ARM)
    implementation( "com.formdev:flatlaf:${flatlafVersion}:windows-arm64@dll" )
    implementation( "com.formdev:flatlaf-extras:${flatlafVersion}" )
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.zane.newpipe.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
